services:
  host-otel-collector:
    privileged: true
    container_name: host-otel-collector
    image: otel/opentelemetry-collector-contrib:latest
    command: --config=/etc/collector/otel-collector-config.yaml
    volumes:
      - ./otel-collector-config.yaml:/etc/collector/otel-collector-config.yaml:ro
      - /:/hostfs:ro # mount host filesystem,  needed for hostmetrics
    ports:
      - "4317:4317"
      - "4318:4318"
      - "8889:8889" # Prometheus exporter
      - "8888:8888" # Prometheus exporter
    networks:
      - otlp
    environment:
      OTEL_RESOURCE_ATTRIBUTES: service.name=srv_232 #Will be picked up by resource detection

  prometheus:
    privileged: true
    container_name: prometheus
    restart: unless-stopped
    image: prom/prometheus:v3.2.1
    command:
      - --web.enable-otlp-receiver
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - /opt/otelcol/prometheus:/prometheus
    ports:
      - "9090:9090"
    networks:
      - otlp
  grafana:
    # depends_on:
    #   - loki
    #   - prometheus
    privileged: true
    container_name: grafana
    restart: unless-stopped
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - /opt/otelcol/grafana:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning/:ro
    networks:
      - otlp

  loki:
    # user: root
    image: grafana/loki:latest
    privileged: true
    container_name: loki
    restart: unless-stopped
    ports:
      - "3100:3100"
    command: ["-config.file=/etc/loki/loki.yaml"]
    volumes:
      - ./loki.yaml:/etc/loki/loki.yaml
      - /opt/otelcol/loki:/loki
    networks:
      - otlp

  init-tempo:
    image: &tempoImage grafana/tempo:latest
    user: root
    entrypoint:
      - "chown"
      - "10001:10001"
      - "/var/tempo"
    volumes:
      - /opt/otelcol/tempo:/var/tempo

  tempo:
    privileged: true
    image: *tempoImage
    container_name: tempo
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
      - /opt/otelcol/tempo:/var/tempo
    ports:
      - "3200" # tempo
    networks:
      - otlp
    depends_on:
      - init-tempo

networks:
  otlp:
# volumes:
#   grafana-storage:
#   prometheus-storage:
#   loki-storage:
#   tempo-storage:
