services:
  host-otel-collector:
    container_name: host-otel-collector
    image: otel/opentelemetry-collector-contrib:latest
    command: --config=/etc/collector/otel-collector-config.yaml
    volumes:
      - ./otel-collector-config.yaml:/etc/collector/otel-collector-config.yaml
      - /:/hostfs # mount host filesystem,  needed for hostmetrics
    ports:
      - "4317:4317"
      - "4318:4318"
      - "8889:8889" # Prometheus exporter
    networks:
      - otlp
    environment:
      - HOSTNAME=${HOSTNAME}

  prometheus:
    container_name: prometheus
    restart: unless-stopped
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-storage:/prometheus
    ports:
      - "9090:9090"
    networks:
      - otlp
  grafana:
    container_name: grafana
    restart: unless-stopped
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning/
    networks:
      - otlp

networks:
  otlp:

volumes:
  grafana-storage:
  prometheus-storage:
