# Receivers
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

  hostmetrics:
    root_path: /hostfs
    collection_interval: 10s
    scrapers:
      cpu:
        metrics:
          system.cpu.utilization:
            enabled: true
          system.cpu.physical.count:
            enabled: true
          system.cpu.logical.count:
            enabled: true
          system.cpu.frequency:
            enabled: true

      load:
      memory:
        metrics:
          system.memory.utilization:
            enabled: true
          system.linux.memory.available:
            enabled: true
          system.memory.limit:
            enabled: true

      disk:
      filesystem:
        metrics:
          system.filesystem.utilization:
            enabled: true

      network:
      processes:
      process:
        mute_process_all_errors: true
      system:

  filelog/var:
    start_at: beginning
    include: [/system_log/*]
    include_file_path: true
    retry_on_failure:
      enabled: true
      max_elapsed_time: 0
    storage: file_storage/filelogreceiver
# Processors
processors:
  memory_limiter:
    check_interval: 1s
    limit_percentage: 80
    spike_limit_percentage: 15

  resourcedetection/env:
    detectors: [env]
    timeout: 2s
    override: false

  batch:

extensions:
  file_storage/filelogreceiver:
    create_directory: true
    directory: /var/lib/otelcol/file_storage/receiver
  file_storage/otlpoutput:
    create_directory: true
    directory: /var/lib/otelcol/file_storage/output

# Exporters
exporters:
  otlphttp/logs:
    endpoint: "http://loki:3100/otlp"
    tls:
      insecure: true

  otlphttp/traces:
    endpoint: "http://tempo:3301"
    tls:
      insecure: true

  otlphttp:
    traces_endpoint: "http://tempo:3301"
    metrics_endpoint: "http://prometheus:9090/api/v1/otlp/v1/metrics"
    logs_endpoint: "http://loki:3100/otlp/v1/logs"
    tls:
      insecure: true
    retry_on_failure:
      enabled: true
    sending_queue:
      storage: file_storage/otlpoutput

  debug:
    verbosity: detailed

  # prometheus/host:
  #   endpoint: "0.0.0.0:8889"
  #   # namespace: host_metrics
  #   resource_to_telemetry_conversion:
  #     enabled: true
  # prometheus/others:
  #   endpoint: "0.0.0.0:8887"
  #   resource_to_telemetry_conversion:
  #     enabled: true

# Pipelines
service:
  extensions: [file_storage/filelogreceiver, file_storage/otlpoutput]
  pipelines:
    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlphttp]

    metrics/host:
      receivers: [hostmetrics]
      processors: [memory_limiter, resourcedetection/env, batch]
      exporters: [otlphttp]

    metrics/others:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlphttp]

    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlphttp]
