# Receivers
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

  hostmetrics:
    collection_interval: 10s
    scrapers:
      cpu:
      load:
      memory:
      disk:
      filesystem:
      network:
      processes:

# Processors
processors:
  memory_limiter:
    check_interval: 1s
    limit_percentage: 80
    spike_limit_percentage: 15

  resourcedetection/env:
    detectors: [env]
    timeout: 2s
    override: false

  batch:

# Exporters
exporters:
  otlphttp/logs:
    endpoint: "http://loki:3100/otlp"
    tls:
      insecure: true
  debug:
    verbosity: detailed

  prometheus/host:
    endpoint: "0.0.0.0:8889"
    namespace: host_metrics
    resource_to_telemetry_conversion:
      enabled: true
  prometheus/others:
    endpoint: "0.0.0.0:8887"
    resource_to_telemetry_conversion:
      enabled: true

# # Pipelines
service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [debug, otlphttp/logs]
    metrics/host:
      receivers: [hostmetrics, postgresql]
      processors: [memory_limiter, resourcedetection/env, batch]
      exporters: [debug, prometheus/host]
    metrics/others:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [debug, prometheus/others]
