# Receivers
receivers:
  filelog:
    include: [/pg_log/*.log]
    retry_on_failure:
      enabled: true
      max_elapsed_time: 0
    storage: file_storage/pg-db
    operators:
      - type: regex_parser
        regex: '/^(?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d{3}) (?P<timezone>EST) \[(?P<process_id>\d+)\] (?P<severity>[A-ZÉÈÊË]+)\s*:\s*(?P<message>.+)$'
        timestamp:
          parse_from: attributes.timestamp
          layout: "%Y-%m-%d %H:%M:%S.%f"
        severity:
          parse_from: attributes.severity

  hostmetrics:
    collection_interval: 10s
    scrapers:
      cpu:
      load:
      memory:
      disk:
      filesystem:
      network:
      processes:

  postgresql:
    endpoint: 192.168.1.224:5432
    transport: tcp
    username: user_beasy
    password: BarnoinBeasyBD@224
    databases: # empty will monitor all databases non-templates.
    collection_interval: 10s
    tls:
      insecure: true

extensions:
  file_storage/pg-db:
    create_directory: true
    directory: /var/lib/otelcol/file_storage/pg-db

# Processors
processors:
  memory_limiter:
    check_interval: 1s
    limit_percentage: 80
    spike_limit_percentage: 15

  resourcedetection/env:
    detectors: [env]
    timeout: 2s
    override: false

  batch:

# Exporters
exporters:
  otlp:
    endpoint: "http://192.168.1.232:4317"
    tls:
      insecure: true

  otlphttp:
    # endpoint: "http://192.168.1.232:4318"
    logs_endpoint: "http://192.168.1.232:4318"
    metrics_endpoint: "http://192.168.1.232:4318"
    tls:
      insecure: true

  otlphttp/logs:
    logs_endpoint: "http://192.168.1.232:4318"
    metrics_endpoint: "http://192.168.1.232:4318"
    retry_on_failure:
      enabled: true
      max_elapsed_time: 0
    sending_queue:
      enabled: true
      queue_size: 100
      storage: file_storage/pg-db
    tls:
      insecure: true

  debug:
    # verbosity: detailed

# Pipelines
service:
  extensions: [file_storage/pg-db]
  pipelines:
    logs/pg:
      receivers: [filelog]
      processors: [memory_limiter, resourcedetection/env, batch]
      exporters: [debug, otlphttp/logs]
    metrics:
      receivers: [hostmetrics, postgresql]
      processors: [memory_limiter, resourcedetection/env, batch]
      exporters: [debug, otlphttp]
